# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02277974abc92749293d35f4d8e595e03bcd55b98af64256812545eb22a7938fdcd94e1bed47b0857affa7eb593886418962ceeb0816c2abea81ba991882c997

test:
  secret_key_base: b8bafdee4e85575e5dadab3f9c9354e2714978e31357fde87c3ba3424fc9a77b348214b97a05c1dd73bcae3a025c8bec2a31c52c966039f9182fe2d85a098075

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
